[workspace]
resolver = "2"
members = [
    "src/paste",
    "src/pastebin"
]

[workspace.dependencies]
actix-web = "4.4.1"
anyhow = "1.0.79"
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde = { version = "1.0.195", features = ["derive"] }

